# Generated by Django 5.2 on 2025-04-03 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Critic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('I', 'IMDB'), ('RT', 'Rotten Tomatoes'), ('M', 'Metacritic')], default='I', max_length=50)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.movie')),
            ],
        ),
    ]
