# Generated by Django 5.2 on 2025-04-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_critic_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critic',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
